[colors]
[colors.primary]
background = "#000000"
foreground = "#cccccc"

[colors.normal]
black   = "#000000"
red     = "#1720ab"
green   = "#13b3f1"
yellow  = "#40b2e3"
blue    = "#1e2cd2"
magenta = "#1134ee"
cyan    = "#5c91b2"
white   = "#97d3df"

[colors.bright]
black   = "#2c3066"
red     = "#303ded"
green   = "#63d2fc"
yellow  = "#8ad6f5"
blue    = "#5c68ef"
magenta = "#5f77fc"
cyan    = "#98bbd2"
white   = "#cccccc"

[colors.cursor]
text   = "#000000"
cursor = "#cccccc"
