# Background and foreground colors
background = #000000
foreground = #cccccc

# Standard colors
palette = 0=#000000
palette = 1=#1720ab
palette = 2=#13b3f1
palette = 3=#40b2e3
palette = 4=#1e2cd2
palette = 5=#1134ee
palette = 6=#5c91b2
palette = 7=#97d3df

# Bright colors
palette = 8=#2c3066
palette = 9=#303ded
palette = 10=#63d2fc
palette = 11=#8ad6f5
palette = 12=#5c68ef
palette = 13=#5f77fc
palette = 14=#98bbd2
palette = 15=#cccccc
