background            #000000
foreground            #cccccc

# black
color0  #000000
color8  #2c3066

# red
color1  #1720ab
color9  #303ded

# green
color2  #13b3f1
color10 #63d2fc

# yellow
color3  #40b2e3
color11 #8ad6f5

# blue
color4  #1e2cd2
color12 #5c68ef

# magenta
color5  #1134ee
color13 #5f77fc

#cyan
color6  #5c91b2
color14 #98bbd2

#white
color7  #97d3df
color15 #cccccc


